import './globals.css';
import type { Metadata } from 'next';
import Layout from '@/components/layout';
import React from "react";


//console.log('---inter---', inter);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Layout>
      <main className="p-4">
        {children}
      </main>
    </Layout>
  )
}
